version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - customer-service
      - account-service
      - transaction-service
      - analytics-service
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  # Customer Service
  customer-service:
    build: ./customer-service
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  # Account Service
  account-service:
    build: ./account-service
    ports:
      - "5003:5003"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  # Transaction Service
  transaction-service:
    build: ./transaction-service
    ports:
      - "5004:5004"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  # Analytics Service
  analytics-service:
    build: ./analytics-service
    ports:
      - "5006:5006"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  # Frontend (React app)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    environment:
      - REACT_APP_API_URL=http://api-gateway:5000
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

