version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - customer-service
      - account-service
      - transaction-service

  customer-service:
    build: ./customer-service
    ports:
      - "5001:5001"

  account-service:
    build: ./account-service
    ports:
      - "5002:5002"

  transaction-service:
    build: ./transaction-service
    ports:
      - "5003:5003"

