version: "3.8"

services:
  # API Gateway service
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - customer-service
      - account-service
      - transaction-service
      - analytics-service

  # Customer Service
  customer-service:
    build:
      context: ./customer-service
    ports:
      - "5001:5000"
    depends_on:
      - account-service

  # Account Service
  account-service:
    build:
      context: ./account-service
    ports:
      - "5002:5000"

  # Transaction Service
  transaction-service:
    build:
      context: ./transaction-service
    ports:
      - "5003:5000"

  # Analytics Service
  analytics-service:
    build:
      context: ./analytics-service
    ports:
      - "5004:5000"

  # Frontend React app (served by Nginx)
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api-gateway
      - customer-service
      - account-service
      - transaction-service
      - analytics-service
