version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - customer-service
      - account-service
      - transaction-service
      - notification-service
      - auth-service
      - analytics-service

  # Customer Service
  customer-service:
    build: ./customer-service
    ports:
      - "5001:5001"

  # Account Service
  account-service:
    build: ./account-service
    ports:
      - "5002:5002"

  # Transaction Service
  transaction-service:
    build: ./transaction-service
    ports:
      - "5003:5003"

  # Notification Service
  notification-service:
    build: ./notification-service
    ports:
      - "5004:5004"

  # Auth Service
  auth-service:
    build: ./auth-service
    ports:
      - "5005:5005"

  # Analytics Service
  analytics-service:
    build: ./analytics-service
    ports:
      - "5006:5006"

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  # RabbitMQ for messaging (optional for communication)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

